services:
  web:
    build: ./app
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://flask:flaskpass@db:5432/flaskdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: flaskr_db
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:

networks:
  default:
    name: devops_net
    external: true
