global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'flask'
    static_configs:
      - targets: ['172.18.0.3:5000']

