name: CD - Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'            # публикация также при релизах, напр. v1.0.0

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      # --- Получаем код ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Настраиваем Docker Buildx ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Входим в Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Сборка и публикация ---
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-hybrid-template:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-hybrid-template:${{ github.run_number }}
